name: Build & Push to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./fe
          file: ./fe/Dockerfile
          push: true
          tags: ghcr.io/dimireme/weather-frontend:latest

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./be
          file: ./be/Dockerfile
          push: true
          tags: ghcr.io/dimireme/weather-backend:latest
